### ISSUE TITLE
I tried the code but always getting a null object on the @Inject instance

### ISSUE THREAD

**Issue by d3bt3ch** [OmarAflak/Dagger2-CYS#1]
I tried the code for SharedPreferences but I am getting a null object in the activity.

**Comment by omaraflak** [comment]
Did you changed anything in the code ? If yes, can you post it here ?

**Comment by d3bt3ch** [comment]
Nothing .... Only on place of ObjectManager mine has a SharedPrefsHelper.

**Comment by omaraflak** [comment]
It tried to run my code again and it's working without any problem... The problem should not be from this code. You can send me your project zipped, I'll take a look at it

**Comment by d3bt3ch** [comment]
Sorry ... It was my mistake. I was trying to inject on my BaseActivity. It is working perfectly. Btw ... How do I inject in BaseActivity or BaseFragment ?

**Comment by omaraflak** [comment]
Non problem. You have to change the `AppComponent` file and add this line :

`void inject(BaseActivity activity);`

Which tells Dagger that you can inject your object into this Activity.
